version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@rmknxqlahheartia_tp?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=BDPRODUCTOMASCOTA
      - SPRING_DATASOURCE_PASSWORD=ActSum.S2_BDJ
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/wallet
    networks:
      - default

networks:
  default:
    driver: bridge


